version: '3.8'
services:
    ac-db:
        image: postgres:12
        ports: 
          - 5432:5432
        environment:
          PGDATA: /var/lib/pgsql/data/
          POSTGRES_PASSWORD: pass
        volumes:
          - "./DEV-etc/ac_db-init/:/docker-entrypoint-initdb.d/"
          - "/tmp/db:/var/lib/pgsql/data/"
#        restart: unless-stopped

    ac-redis:
        image: redis:latest
        ports:
          - 6379:6379
#        restart: unless-stopped          

    ac-api:
        image: git.disoft.us:5050/nastya/ac-back:basic
        command: >
            bash -c "ls -lah && pwd && pip3 install -r requirements.txt  && python3 manage.py test --parallel --noinput"
        environment:
          WAIT_HOSTS: ac-db:5432
        ports: 
          - 9191:9191
        volumes:
          - "./:/usr/ac-back/"
        depends_on:
          - ac-db
          - ac-redis
#        restart: unless-stopped

